export const queries = {
  contains: 'CT',
  'does not contain': 'XCT',
  'contains user': 'HAS',
  'does not contain user': 'XHAS',
  is: 'EX',
  'is not': 'XEX',
  'starts with': 'SW',
  'does not start with': 'XSW',
  'on or before': 'OBF',
  'on or after': 'OAF',
  before: 'BF',
  after: 'AF',
  'in range': 'IR',
  'not in range': 'XIR',
  'less than': 'LT',
  'less than or equal to': 'LTE',
  'greater than': 'GT',
  'greater than or equal to': 'GTE',
};
